version: '3'

services:
  backend:
    build:
      context: ./
    container_name: backend
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 8501:80